# Generated by Django 4.2.30 on 2026-05-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('input_format', models.TextField(verbose_name='Formato de entrada')),
                ('output_format', models.TextField(verbose_name='Formato de salida')),
                ('sample_input', models.TextField(blank=True, default='', verbose_name='Entrada de ejemplo')),
                ('sample_output', models.TextField(blank=True, default='', verbose_name='Salida de ejemplo')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=10, verbose_name='Dificultad')),
                ('time_limit_ms', models.IntegerField(default=2000, verbose_name='Límite de tiempo (ms)')),
                ('memory_limit_kb', models.IntegerField(default=262144, verbose_name='Límite de memoria (KB)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
                'db_table': 'problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Datos de entrada')),
                ('expected_output', models.TextField(verbose_name='Salida esperada')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Es ejemplo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem', verbose_name='Problema')),
            ],
            options={
                'verbose_name': 'Caso de prueba',
                'verbose_name_plural': 'Casos de prueba',
                'db_table': 'test_cases',
                'ordering': ['order'],
            },
        ),
    ]
