# Generated by Django 4.2.30 on 2026-05-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'En curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pública')),
                ('scoring_type', models.CharField(choices=[('icpc', 'ICPC (Penalización)'), ('ioi', 'IOI (Puntos parciales)')], default='icpc', max_length=10, verbose_name='Tipo de puntuación')),
                ('penalty_time', models.IntegerField(default=20, verbose_name='Penalización por intento fallido (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'contests',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'contest_participants',
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='Etiqueta (A, B, C...)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Problema de competencia',
                'verbose_name_plural': 'Problemas de competencia',
                'db_table': 'contest_problems',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_count', models.IntegerField(default=0, verbose_name='Problemas resueltos')),
                ('total_penalty', models.IntegerField(default=0, verbose_name='Penalización total (min)')),
                ('score', models.IntegerField(default=0, verbose_name='Puntaje')),
                ('rank_position', models.IntegerField(default=0, verbose_name='Posición')),
                ('last_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Último AC')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='contests.contest', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'db_table': 'rankings',
                'ordering': ['-solved_count', 'total_penalty'],
            },
        ),
    ]
