# Generated by Django 4.2.30 on 2026-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Por Equipos')], default='individual', max_length=20, verbose_name='Modalidad'),
        ),
    ]
