# Generated by Django 4.2.30 on 2026-05-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java')], max_length=20, verbose_name='Lenguaje')),
                ('source_code', models.TextField(verbose_name='Código fuente')),
                ('verdict', models.CharField(choices=[('pending', 'Pendiente'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='pending', max_length=10, verbose_name='Veredicto')),
                ('execution_time_ms', models.IntegerField(default=0, verbose_name='Tiempo de ejecución (ms)')),
                ('memory_used_kb', models.IntegerField(default=0, verbose_name='Memoria usada (KB)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('test_cases_passed', models.IntegerField(default=0, verbose_name='Casos de prueba pasados')),
                ('total_test_cases', models.IntegerField(default=0, verbose_name='Total de casos de prueba')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest', verbose_name='Competencia')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='Problema')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
