# Generated by Django 4.2.30 on 2026-06-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='Retroalimentación de la IA'),
        ),
    ]
