# Generated by Django 4.2.30 on 2026-05-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'db_table': 'trainings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_problems', to='problems.problem', verbose_name='Problema')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_problems', to='trainings.training', verbose_name='Entrenamiento')),
            ],
            options={
                'verbose_name': 'Problema de entrenamiento',
                'verbose_name_plural': 'Problemas de entrenamiento',
                'db_table': 'training_problems',
                'ordering': ['order'],
            },
        ),
    ]
